name: Go CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...
      env:
        MONGODB_URI: mongodb://localhost:27017
        DB_NAME: logs_test
        COLLECTION_NAME: logs

    - name: Run tests with race detection
      run: go test -race ./...
      env:
        MONGODB_URI: mongodb://localhost:27017
        DB_NAME: logs_test
        COLLECTION_NAME: logs

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v -o log-ingestor

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: log-ingestor
        path: log-ingestor
        retention-days: 5 